# Generated by Django 5.2.4 on 2025-07-28 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Unique identification number for the employee.', max_length=20, unique=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='Time when the employee started the test.')),
                ('end_time', models.DateTimeField(blank=True, help_text='Time when the employee submitted or timed out.', null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text="Employee's score (e.g., percentage).", max_digits=5, null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='True if the test attempt has been submitted.')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeeprofile')),
                ('test_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.testschedule')),
            ],
            options={
                'ordering': ['-start_time'],
                'unique_together': {('employee', 'test_schedule')},
            },
        ),
    ]
