# Generated by Django 5.2.4 on 2025-07-28 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Select the correct option (A, B, C, or D).', max_length=1)),
                ('marks', models.DecimalField(decimal_places=2, default=1.0, help_text='Marks awarded for correctly answering this question.', max_digits=5)),
                ('technology', models.ForeignKey(help_text='The technology this question belongs to.', on_delete=django.db.models.deletion.CASCADE, to='administrator.technology')),
            ],
            options={
                'ordering': ['technology', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='The option selected by the employee (Null if not answered).', max_length=1, null=True)),
                ('test_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='employee.employeetestattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionbank.question')),
            ],
            options={
                'ordering': ['question__id'],
                'unique_together': {('test_attempt', 'question')},
            },
        ),
    ]
