# Generated by Django 5.2.4 on 2025-07-28 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Python, Django, SQL', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='TestSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='The date and time when the test becomes available.')),
                ('end_time', models.DateTimeField(help_text='The date and time when the test is no longer available.')),
                ('duration_minutes', models.IntegerField(default=60, help_text='Duration of the test in minutes.')),
                ('total_questions', models.IntegerField(default=50, help_text='Number of questions to randomly select for this test.')),
                ('is_active', models.BooleanField(default=False, help_text='Check to make this test schedule active and visible to employees.')),
                ('technology', models.ForeignKey(help_text='The technology this test is for.', on_delete=django.db.models.deletion.CASCADE, to='administrator.technology')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
